sonar.projectKey=test-service-back
sonar.projectName=test_service_back
sonar.language=python
sonar.sources=.
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=nosetests.xml
sonar.python.xunit.skipDetails=false
sonar.coverage.dtdVerification=false
sonar.coverage.exclusions=\
    **/tests/**,\
    **/**_module.py,\
    **/__main__.py,\
    **/app.py,\
    **/scripts/**,\
    **/generated/**,\
    **/contracts/**,\
    **/ci/**,\
    **/scripts/**
sonar.cpd.exclusions=\
    **/generated/**,\
    **/contracts/**,\
    **/tests/**,\
    **/scripts/**
sonar.exclusions=\
    **/generated/**,\
    **/contracts/**,\
    **/scripts/**
