name: test-service
services:
  postgres:
    image: postgres:15
    container_name: test-service-db
    environment:
      POSTGRES_DB: test_service
      POSTGRES_USER: postgresqldba
      POSTGRES_PASSWORD: admin
    ports:
      - "${POSTGRES_PORT:-55434}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    networks:
      - test-service
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgresqldba -d test_service"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
